### ISSUE TITLE
ls-write-version doesn't write licenses

### ISSUE THREAD

**Issue by eed3si9n** [softprops/ls#25]
## steps

```
> show licenses
[info] List((MIT License,https://xxx/LICENSE))
> ls-write-version
```
## problem

the generated file doesn't contain the licenses.

```
 "licenses": [],
```
## expectation

```
 "licenses": [{
   "name": "MIT License",
   "url":"https://xxx/LICENSE"
  }],
```

**Comment by softprops** [comment]
Thanks Eugene. I can always count on you as an early adopter.

I'll look into this today after I get something to eat and going for a walk. I was up way too late last night and need to refresh myself :)

Quick question though:

Are you using 0.11.0 or 0.11.1 and are you still using the 0.1.0-RC or the 0.1.0 version I published last night?

I ran into [this issue](https://github.com/harrah/xsbt/issues/257#issuecomment-2871776) last night with the project only using 0.11.1. The symptom was a class not found exception reported when loading ls.License when loading the project. I hopefully fixed that by carefully publishing the common module first then depending on that as a library dep (not module dep) before publishing the plugin module. It think its fixed in sbt's master so I should be in 0.11.2. 

In any case... try to ping me back with confirmation the version info for sbt and plugin info. Thanks!

**Comment by softprops** [comment]
Oh, just thought of this. licenses is [scoped to the lsync task](https://github.com/softprops/ls/blob/master/plugin/src/main/scala/ls.scala#L386) in ls since its an sbt built-in. Try and verify what you get in `licenses(for lsync)` in the shell. That may be a clue.

**Comment by softprops** [comment]
I tested with a simple set up

```
seq(lsSettings :_*)

(LsKeys.host in LsKeys.lsync) := "http://localhost:5000"

(licenses in LsKeys.lsync) := Seq(("MIT",url("http://localhost:5000")))
```

I checked the scoped key

```
> show licenses(for lsync)
[info] List((MIT,http://localhost:5000))
```

Also can you do a `show` on `ls-version-info`. That's basically a data struct that holds what gets written in the version file

```
> show ls-version-info
[info] VersionInfo(me.lessis,default,0.1.0-  SNAPSHOT,Optionals(default,None,List(),None,List(License(MIT,http://localhost:5000))),List(Scala-Tools Maven2 Repository: http://scala-tools.org/repo-releases),List(),List(2.9.1),false)
```

It looks like it worked in this case

```
> ls-write-version
[info] Wrote /Users/dougtangren/Desktop/app/src/main/ls/0.1.0.json
[success] Total time: 0 s, completed Nov 25, 2011 3:28:01 PM
```

> exit 
>     ~/Desktop/app ✈ cat /Users/dougtangren/Desktop/app/src/main/ls/0.1.0.json

```
{
 "organization":"me.lessis",
 "name":"default",
 "version":"0.1.0-SNAPSHOT",
 "description":"default",
 "site":"",
 "tags":[],
 "docs":"",
 "licenses": [{
   "name": "MIT",
   "url": "http://localhost:5000"
  }],
 "resolvers": ["http://scala-tools.org/repo-releases"],
 "dependencies": [],
 "scalas": ["2.9.1"],
 "sbt": false
}
```

**Comment by eed3si9n** [comment]
sorry I was out all day. yea, so I set plain `licenses` key:

```
licenses := Seq("MIT License" -> url("https://github.com/eed3si9n/scalaxb/blob/master/LICENSE")),
```

I didn't even think to scope this in `lsync`. 

```
licenses in lsync <<= licenses in GlobalScope,
```

instead of the above I did the following and it worked

```
licenses in lsync <<= licenses
```

**Comment by softprops** [comment]
Come to think about it the default should `just work` since its it defaults to the Global scope. Maybe thats not the right scope to use by default. In any case, I'll leave the bug up try to verify the defaults are actually doing what I think they are. 

Thanks for trying this out for me.

**Comment by eed3si9n** [comment]
I have a multi-project build, and put the `licenses` in the unscoped common setting, but I was running `lsync` in a subproject, so `licenses` was scoped at least by the project.

**Comment by softprops** [comment]
Thanks eugene, I'll do more testing today
