### ISSUE TITLE
ls-try and ls-install missing from tasks

### ISSUE THREAD

**Issue by dcsobral** [softprops/ls#44]
When I list tasks on sbt console, ls-try and ls-install are not shown.

**Comment by softprops** [comment]
Are you sure you've mixed in `seq(lsSettings:_*)` to your build definition?

**Comment by dcsobral** [comment]
It's in a `.sbt/ls.sbt` file, and I tried putting it on `build.sbt` on my project, and `tasks` still doesn't show them. I can _use_ them, but they are not shown.

**Comment by softprops** [comment]
Oh Sorry, I miss read this. `ls-try` and `ls-install` are not `tasks`. They are `commands`. That's why they are not listed when invoking the `tasks` command on the repl. Commands are actually stored under a projects [commands key](https://github.com/softprops/ls/blob/0.1.1/plugin/src/main/scala/ls.scala#L391) of a build definition. I talked with Mark for a while about wanting to do these as tasks but he said anything that modifies global state like ls-try and install do should be implemented as commands.
