### ISSUE TITLE
Please publish for sbt-0.12.0-RC1

### ISSUE THREAD

**Issue by etorreborre** [softprops/ls#62]
Thanks!

**Comment by softprops** [comment]
I'll get to publishing it this weekend. sorry for any inconvenience @etorreborre

**Comment by softprops** [comment]
[Fixed](http://notes.implicit.ly/post/24939501996/ls-sbt-0-1-2)

```
sbtAddPlugin("me.lessis" % "ls-sbt" % "0.1.2")
```

**Comment by etorreborre** [comment]
Sorry that doesn't work for me. I get:

```
module not found:
http://scalasbt.artifactoryonline.com/scalasbt/sbt-plugin-releases/me.lessis/ls_2.9.2/0.1.2/ivys/ivy.xml
```

Is it a problem on my side or on your side?

**Comment by softprops** [comment]
Ah. add this to your plugins.sbt file

```
resolvers += Opts.resolver.sonatypeReleases
```

There's a common lib artifact published to sonatype. sbt plugins are generally published to the sbt ivy host while releases are generally published to the sonatype host. Since that's going to be the case 80% I wish those were configured by default in sbt going forward

**Comment by softprops** [comment]
Actually I take that back. I believe the sonatype oss hosted artifacts eventually get mirrored over to maven central after some lag. the ls artifact probably hasn't made its way over yet. So the line above should only be temporarily necessary.

**Comment by etorreborre** [comment]
Ok, thanks Doug. I confirm that it's working fine with that line. I'll remove it tomorrow to check if the mirroring is good too.
